version: '3'

services:
  autova:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      autova_network:


  zap:
      image: owasp/zap2docker-stable
      user: zap
      ports:
        - 8080:8080
        - 8090:8090
      command: zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
      networks:
        autova_network:

networks:
  autova_network:
